apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: app-slug
spec:
  title: Withdrawal genie
  icon: https://cdn-icons-png.flaticon.com/512/5024/5024665.png
  statusInformers:
    - deployment/example-nginx
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
